site_name: 'Mottainai docs'
site_description: 'Documentation for Mottainai'
site_author: 'Mottainai'
site_url: 'https://mottainaici.github.io/docs/'

repo_name: 'MottainaiCI/docs'
repo_url: https://github.com/MottainaiCI/docs

nav:
- Home: index.md
- How it works: general.md
- Usage:
  - Cli: usage/cli.md
  - 'Tasks and Pipelines': usage/tasksandpipelines.md
  - Plans: usage/plans.md
  - Artefacts: usage/artefacts.md
  - Namespaces: usage/namespace.md
  - Storages: usage/storage.md

theme:
  name: 'material'
  logo: 'images/logo.png'
  palette:
    primary: 'cyan'
    accent: 'cyan'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

repo_name: 'MottainaiCI/mottainai-server'
repo_url: 'https://github.com/MottainaiCI/mottainai-server'
